baseURL = ""
themesdir = "../.."
title = "Hugo theme for Vivliosytle-cli."
theme = "hugo-theme-vivliocli"
languageCode = "ja-jp"
DefaultContentLanguage = "jp"
enableInlineShortcodes = true
disablePathToLower= true
enableGitInfo = false
defaultContentLanguageInSubdir= true
hasCJKLanguage = true
uglyurls = true
relativeURLs = true

[params]
    theme_css = ["/css/vivlio-theme-manual.css"]
    isPDF = false
    #showIfs = ["edition1", "edition2"]
    only_showIfs = false
    flat_toc = false

[languages]
  [languages.jp]
    htmlLang = "ja"
    languageName = "Japanese"
    contentDir = "content/jp"
    weight = 1
    dateFormat = "2006年01月02日"
  [languages.en]
    htmlLang = "en"
    languageName = "English"
    contentDir = "content/en"
    weight = 2
    dateFormat = "Jan. 2, 2006"

# goldmark settings
[markup.goldmark.renderer]
  hardWraps = true
  unsafe = true

