publishDir = "public_pdf_sample"

[params]
  isPDF = true
  theme_css = [
    "/css/vivlio-theme-manual.css",
    #"/css/vivlio-theme-manual-bookoption.css" # add book style (consider left/right page)
    ]
  showIfs = ["edition1", "edition2"]
  only_showIfs = false
  flat_toc = false
